map_country_name <- c(
  "at" = "Austria",
  "ch" = "Switzerland",
  "dk" = "Denmark",
  "ee" = "Estonia",
  "es" = "Spain",
  "fi" = "Finland",
  "fr" = "France",
  "gr" = "Greece",
  "hr" = "Croatia",
  "hu" = "Hungary",
  "it" = "Italy",
  "lt" = "Lithuania",
  "mt" = "Malta",
  "pl" = "Poland",
  "pt" = "Portugal",
  "si" = "Slovenia",
  "sk" = "Slovakia",
  "uk" = "United Kingdom",
  "be" = "Belgium",
  "de" = "Germany",
  "nl" = "Netherlands"
)

map_country_group <- c(
  "at" = "G1",
  "ch" = "G2",
  "dk" = "G1",
  "ee" = "G3",
  "es" = "G1",
  "fi" = "G2",
  "fr" = "G1",
  "gr" = "G2",
  "hr" = "G3",
  "hu" = "G3",
  "it" = "G1",
  "lt" = "G2",
  "mt" = "G3",
  "pl" = "G1",
  "pt" = "G1",
  "si" = "G2",
  "sk" = "G3",
  "uk" = "G0",
  "be" = "G0",
  "de" = "G0",
  "nl" = "G0"
)